services:
  kingtower2:
    image: bannerbrawl-base:v1.0
    ports:
      - "30023:22"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    cap_add:
      - NET_ADMIN # for zerotier
      - SYS_ADMIN
    devices:
      - /dev/net/tun
